<!DOCTYPE HTML>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Selenium, Capybara, ChromeDriver: connection refused error debugging - Ryan Bigg</title>
  <link rel="shortcut icon" href="https://ryanbigg.com/favicon.png" type="image/x-icon">
  <link href="/feed.xml" rel="alternate" title="RyanBigg.com" type="application/atom+xml" />
  <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,700|Ubuntu+Mono:400,700,700i&display=swap"
    rel="stylesheet">
  <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>
  <link rel='stylesheet' href='/css/style.css' media='screen'>
  <link rel='stylesheet' href='/css/highlighting.css' media='screen'>
  <script src="/js/highlight.js"></script>
  <script>hljs.highlightAll();</script>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  
  <meta content="Ryan Bigg - Selenium, Capybara, ChromeDriver: connection refused error debugging" property="og:title">
  
  <meta property="og:site_name" content="Ryan Bigg">
  
  <meta content="https://ryanbigg.com/2020/08/selenium-capybara-chromedriver-connection-refused-error-debugging" property="og:url">
  
  
  <meta content="" property="og:description">
  
  <meta property="og:type" content="article">
  <meta property="og:image" content="https://ryanbigg.com/images/og.png">
</head>


<body>
  <div class="main">
    <div class='content'>
      <div class='content-inner'>
        <article>
          <div class='text-center mb-8'>
            <a href="/blog">&#x27F5; Posts</a>
            <a href="/2020/08/selenium-capybara-chromedriver-connection-refused-error-debugging">
              <h2>Selenium, Capybara, ChromeDriver: connection refused error debugging</h2>
            </a>
            <small>29 Aug 2020</small>
          </div>
          <p>A few days ago, we started seeing this exception happening for <em>some</em> of our Capybara feature tests:</p>

<pre><code>1.1) Failure/Error: visit(sign_out_path)

      Selenium::WebDriver::Error::UnknownError:
        java.net.ConnectException: Connection refused (Connection refused)
      # [remote server] org.openqa.selenium.remote.server.WebDriverServlet(WebDriverServlet.java):240:in `lambda$handle$0'
      # [remote server] java.util.concurrent.Executors$RunnableAdapter(Executors.java):511:in `call'
      # [remote server] java.util.concurrent.FutureTask(FutureTask.java):266:in `run'
      # [remote server] java.util.concurrent.ThreadPoolExecutor(ThreadPoolExecutor.java):1149:in `runWorker'
      # [remote server] java.util.concurrent.ThreadPoolExecutor$Worker(ThreadPoolExecutor.java):624:in `run'
      # [remote server] java.lang.Thread(Thread.java):748:in `run'
      # ./spec/support/pages/login.rb:5:in `login'
      # ./spec/concepts/extraction/keyboard_shortcuts_spec.rb:84:in `block (2 levels) in &lt;main&gt;'
      # ./spec/spec_helper.rb:69:in `block (2 levels) in &lt;main&gt;'
      # ./spec/support/elasticsearch_spec_helper.rb:42:in `block (3 levels) in &lt;main&gt;'
      # ./spec/support/elasticsearch_spec_helper.rb:38:in `block (2 levels) in &lt;main&gt;'
</code></pre>

<p>Connection refused, fine. But connection refused to <em>what</em>? This error message doesn’t give us much to go on.</p>

<p>Seemingly nothing that we changed had caused this issue – it was one of those types of issues that just popped up spontaneously.</p>

<p>It turns out that this is due to a bug within Google ChromeDriver <code>85.0.4183.83</code>. Here’s the bug report for ChromeDriver: <a href="https://bugs.chromium.org/p/chromedriver/issues/detail?id=3578">Issue 3578</a>.</p>

<h2 id="debugging-steps">Debugging steps</h2>

<p>After quite a lot of playing around with our Docker container setup, building EC2 instances and testing things out there… I was able to track it down to this issue by adding this line to the configuration for our tests:</p>

<pre><code>Selenium::WebDriver.logger.level = Logger::DEBUG
</code></pre>

<p>I knew of this trick by having to debug Selenium issues in the past – it’s a very helpful trick to get messages out of Selenium WebDriver that you wouldn’t otherwise see.</p>

<p>When I did this, I saw these messages come through:</p>

<pre><code>2020-08-30 08:39:15 INFO Selenium &lt;- {"value":{"data":{"text":"{Alert text : "},"error":"unexpected alert open","message":"unexpected alert open: {Alert text : }\n  (Session info: chrome=85.0.4183.83)","stacktrace":"0   chromedriver                        0x000000010a9261b9 chromedriver + 4911545\n1   chromedriver                        0x000000010a8c5e03 chromedriver + 4517379\n2   chromedriver                        0x000000010a533da6 chromedriver + 773542\n3   chromedriver                        0x000000010a4c4072 chromedriver + 315506\n4   chromedriver                        0x000000010a4b7c23 chromedriver + 265251\n5   chromedriver                        0x000000010a491720 chromedriver + 108320\n6   chromedriver                        0x000000010a492693 chromedriver + 112275\n7   chromedriver                        0x000000010a8eef72 chromedriver + 4685682\n8   chromedriver                        0x000000010a8fcb3a chromedriver + 4741946\n9   chromedriver                        0x000000010a8fc801 chromedriver + 4741121\n10  chromedriver                        0x000000010a8d225e chromedriver + 4567646\n11  chromedriver                        0x000000010a8fd061 chromedriver + 4743265\n12  chromedriver                        0x000000010a8e3d0a chromedriver + 4640010\n13  chromedriver                        0x000000010a9160ba chromedriver + 4845754\n14  chromedriver                        0x000000010a92c387 chromedriver + 4936583\n15  libsystem_pthread.dylib             0x00007fff67652109 _pthread_start + 148\n16  libsystem_pthread.dylib             0x00007fff6764db8b thread_start + 15\n"}}
</code></pre>

<p>Well that looks like a crash!</p>

<p>An unexpected alert open? What does that mean?</p>

<p>This lead me to look through the issue logs for Capybara first, as these were tests using Capybara. The final “exit” point from our code uses Capybara code. When I looked on Capybara’s issue tracker I saw that there’s an issue for this problem: <a href="https://github.com/teamcapybara/capybara/issues/2382">Capybara Issue #2382</a>. This then links to a Selenium issue: <a href="https://github.com/SeleniumHQ/selenium/issues/8638">Selenium Issue #8638</a>, which itself then links to <a href="https://bugs.chromium.org/p/chromedriver/issues/detail?id=3578">Issue 3578</a>.</p>

<p>These are pretty good pieces of evidence that indicate it was a chromedriver issue. I then recalled that a colleague of mine, Luiz, mentioned that Chrome had updated a few days ago. An update of Chrome leads to an update in Chromedriver, and since it was Chromedriver that was breaking, I thought to check that.</p>

<p>On the Capybara issue, there are some good steps to reproduce the issue with a minimal test case. I used this to lock Chromedriver to the more modern version:</p>

<pre><code>Webdrivers::Chromedriver.required_version = '85.0.4183.87'
</code></pre>

<p>The issue reported on Capybara wasn’t happening with that <code>.87</code> release, but it <em>does</em> happen with this:</p>

<pre><code>Webdrivers::Chromedriver.required_version = '85.0.4183.83'
</code></pre>

<p>So this then indicates that it’s a particular version of Chromedriver that causes the issue.</p>

<p>There are at least two ways to fix this issue.</p>

<p>The first is to lock Chromedriver using <code>Webdrivers::Chromedriver.required_version</code> to a particular version. But that means we need to remember to update that.</p>

<p>The second way is to dismiss the alert before finishing the test:</p>

<pre><code class="language-ruby">require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'capybara'
  gem 'puma'
  gem 'selenium-webdriver'
  gem 'webdrivers'
  gem 'byebug'
  gem 'pry'
end

require 'selenium-webdriver'
require 'capybara/dsl'

Webdrivers::Chromedriver.required_version = '85.0.4183.83'
Selenium::WebDriver.logger.level = Logger::DEBUG

html = &lt;&lt;~HTML
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
  &lt;head&gt;
    &lt;title&gt;Hello World&lt;/title&gt;
    &lt;meta charset="utf-8"&gt;

    &lt;script type="text/javascript"&gt;
      window.addEventListener('beforeunload', (event) =&gt; {
        event.preventDefault();
        event.returnValue = '';
      });
    &lt;/script&gt;
  &lt;/head&gt;
  &lt;body&gt;
    &lt;h1&gt;&lt;a href="https://google.com"&gt;Hello World&lt;/a&gt;&lt;/h1&gt;
  &lt;/body&gt;
&lt;/html&gt;
HTML

app = proc { |env| [200, { "Content-Type" =&gt; "text/html" }, [html] ] }

session = Capybara::Session.new(:selenium_chrome, app)
session.visit '/'
session.click_on 'Hello World' # interact with the page, to get Chrome to fire `beforeunload`
session.driver.browser.switch_to.alert.accept
session.visit '/'
</code></pre>

<p>It’s the third-to-last and second-to-last lines here that will work around the issue here – we need to attempt to navigate away from the page and then click the alert. Then we can carry on testing after that point.</p>

        </article>
      </div>
    </div>
  </div>
  <footer>
</footer>


  <script>
    (function (i, s, o, g, r, a, m) {
      i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
        (i[r].q = i[r].q || []).push(arguments)
      }, i[r].l = 1 * new Date(); a = s.createElement(o),
        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-60556315-1', 'auto');
    ga('send', 'pageview');

  </script>
</body>

</html>
